### ISSUE TITLE
Result not corresponding

### ISSUE THREAD

**Issue by clausmichele** [taowenleon/video_interpolation#1]
![result](https://user-images.githubusercontent.com/31700619/38737138-97b867dc-3f2e-11e8-86c4-481a491dc4f6.png)
Hi,
I have just tried your network using predict.py and the checkpoint files in the ckp_backup folder, but I get different result compared to the one in the presented picture. The strange thing is that all the values are the same except the PSNR.
Did you correct how you calculate the PSNR after taking that screenshot?

**Comment by taowenleon** [comment]
Hi, I am so sorry the results the the figure is not correct. The PSNR is miscalculated before, I fixed the bug a few days ago. Please refer to the current PSNR value.
